import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
const A='00000000-0000-4000-8000-000000000001', B='00000000-0000-4000-8000-000000000002', C='00000000-0000-4000-8000-000000000003';
test('database: quotas, RLS, invites, UUID ownership and Stripe idempotency', async () => {
  const db = new PGlite();
  try {
    await db.exec(await fs.readFile(new URL('./schema.sql',import.meta.url),'utf8'));
    await db.exec(`insert into auth.users(id,email) values('${A}','a@test.invalid'),('${B}','b@test.invalid'),('${C}','c@test.invalid');`);
    await db.exec(await fs.readFile(new URL('../supabase/migrations/202609060001_audit_hardening.sql',import.meta.url),'utf8'));
    const asUser=async id=>db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${id}',false);`);
    await asUser(A);
    for(let i=0;i<10;i++)await db.exec(`insert into songs(owner_id,title) values('${A}','song ${i}');`);
    await assert.rejects(db.exec(`insert into songs(owner_id,title) values('${A}','11');`),/10 músicas/);
    await assert.rejects(db.exec(`insert into user_subscriptions(user_id,plan_type) values('${A}','pro');`),/permission denied/);
    await assert.rejects(db.exec(`update user_subscriptions set plan_type='pro';`),/permission denied/);
    await assert.rejects(db.exec(`insert into songs(owner_id,title) values('${B}','forged');`),/row-level security/);
    const show=(await db.query(`insert into setlists(owner_id,event_name) values('${A}','Show') returning id`)).rows[0].id;
    await assert.rejects(db.exec(`insert into setlists(owner_id,event_name) values('${A}','Extra')`),/1 repertório/);
    await assert.rejects(db.query('select create_setlist_invite($1)',[show]),/dono assinante/);
    await db.exec(`reset role; insert into user_subscriptions(user_id,plan_type) values('${A}','base') on conflict(user_id) do update set plan_type='base';`);
    await asUser(A);
    await db.exec(`insert into songs(owner_id,title) values('${A}','Base song 11');`);
    const token=(await db.query('select create_setlist_invite($1) token',[show])).rows[0].token;
    const song=(await db.query('select id from songs limit 1')).rows[0].id;
    await db.query(`insert into setlist_items(setlist_id,song_id,item_type,order_index) values($1,$2,'song',0)`,[show,song]);
    await asUser(B);
    assert.equal((await db.query('select * from songs')).rows.length,0);
    assert.equal((await db.query('select * from setlists')).rows.length,0);
    await assert.rejects(db.query('insert into setlist_members(setlist_id,user_id,member_email) values($1,$2,$3)',[show,B,'b@test.invalid']),/permission denied/);
    await assert.rejects(db.query('select accept_setlist_invite($1,$2)',[show,'fake']),/inválido/);
    await db.query('select accept_setlist_invite($1,$2)',[show,token]);
    assert.equal((await db.query('select * from songs')).rows.length,1);
    await assert.rejects(db.query(`insert into setlist_items(setlist_id,item_type,content,order_index) values($1,'divider','bad',1)`,[show]),/row-level security/);
    assert.equal((await db.query(`update songs set title='hacked' returning id`)).rows.length,0);
    await assert.rejects(db.exec(`insert into setlists(owner_id,event_name) values('${B}','Over quota')`),/1 repertório/);
    await db.exec(`reset role; insert into user_subscriptions(user_id,plan_type) values('${B}','pro') on conflict(user_id) do update set plan_type='pro';`);
    await asUser(B);
    await db.query(`insert into setlist_items(setlist_id,item_type,content,order_index) values($1,'divider','OK',1)`,[show]);
    const itemIds=(await db.query('select id from setlist_items order by order_index')).rows.map(r=>r.id).reverse();
    await db.query('select reorder_setlist($1,$2)',[show,itemIds]);
    assert.deepEqual((await db.query('select id from setlist_items order by order_index')).rows.map(r=>r.id),itemIds);
    await assert.rejects(db.query('update setlists set owner_id=$1 where id=$2',[B,show]),/Ownership/);
    await asUser(A);
    await db.query('select create_setlist_invite($1)',[show]);
    await asUser(C);
    await assert.rejects(db.query('select accept_setlist_invite($1,$2)',[show,token]),/inválido/);
    await db.exec(`reset role; update auth.users set email='changed@test.invalid' where id='${A}';`);
    await asUser(A);
    assert.equal((await db.query('select * from songs')).rows.length,11);
    await assert.rejects(db.query("select apply_stripe_subscription('x',1,$1,'cus','sub','pro','active',null)",[A]),/permission denied/);
    await db.exec('reset role; set role service_role;');
    await db.query("select apply_stripe_subscription('new',100,$1,'cus','sub','pro','active',null)",[A]);
    await db.query("select apply_stripe_subscription('old',50,$1,'cus','sub','free','canceled',null)",[A]);
    await db.query("select apply_stripe_subscription('new',100,$1,'cus','sub','free','canceled',null)",[A]);
    assert.equal((await db.query('select plan_type from user_subscriptions where user_id=$1',[A])).rows[0].plan_type,'pro');
    const attempt = (await db.query("select (claim_checkout($1,'base')).request_id id",[C])).rows[0].id;
    assert.equal((await db.query("select (claim_checkout($1,'base')).request_id id",[C])).rows[0].id,attempt);
    await assert.rejects(db.query("select claim_checkout($1,'pro')",[C]),/outro plano/);
    await db.exec('reset role; set role anon;');
    await assert.rejects(db.query('select * from songs'),/permission denied/);
  } finally { await db.close(); }
});
